# Generated by Django 5.1.4 on 2025-01-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_auto_20191129_2003'),
        ('tasks_app', '0002_remove_goal_duration'),
        ('tasks_app', '0004_task_task_done'),
    ]

    operations = [
    ]
